language: python
python:
  - "3.6"
# install dependencies
install:
  - pip install -r requirements.txt
# run test scripts
script:
  - flake8
  - coverage erase
  - pytest --cov
# run coveralls after successful tests
after_success:
  - coveralls
